///|
const TABLE_METADATA : String = "metadata"

///|
const TABLE_SESSIONS : String = "sessions"

///|
const TABLE_AUTHORIZATIONS : String = "authorizations"

///|
const INDEX_ONE_ACTIVE_DEVICE : String = "one_active_device"

///|
const TRIGGER_AUTHORIZATIONS_REQUIRE_SESSION_INSERT : String = "authorizations_require_session_insert"

///|
const TRIGGER_AUTHORIZATIONS_REQUIRE_SESSION_UPDATE : String = "authorizations_require_session_update"

///|
const TRIGGER_SESSIONS_PRESERVE_AUTHORIZATION_PARENT : String = "sessions_preserve_authorization_parent"

///|
const TRIGGER_SESSIONS_DELETE_AUTHORIZATIONS : String = "sessions_delete_authorizations"

///|
const COLUMN_NAME : String = "name"

///|
const COLUMN_VALUE : String = "value"

///|
const COLUMN_ID : String = "id"

///|
const COLUMN_CSRF : String = "csrf"

///|
const COLUMN_EXPIRES : String = "expires"

///|
const COLUMN_EPOCH : String = "epoch"

///|
const COLUMN_USER_ID : String = "user_id"

///|
const COLUMN_LOGIN : String = "login"

///|
const COLUMN_TOKENS : String = "tokens"

///|
const COLUMN_ACCESS_EXPIRES : String = "access_expires"

///|
const COLUMN_REFRESH_EXPIRES : String = "refresh_expires"

///|
const COLUMN_SESSION_ID : String = "session_id"

///|
const COLUMN_TARGET_ID : String = "target_id"

///|
const COLUMN_PHASE : String = "phase"

///|
const COLUMN_CREDENTIALS : String = "credentials"

///|
const COLUMN_USER_CODE : String = "user_code"

///|
const COLUMN_VERIFICATION_URI : String = "verification_uri"

///|
const COLUMN_NEXT_POLL : String = "next_poll"

///|
const COLUMN_INTERVAL : String = "interval"

///|
const COLUMN_BACKOFF : String = "backoff"

///|
const COLUMN_TOKEN_ISSUED : String = "token_issued"

///|
const COLUMN_MESSAGE : String = "message"
