///|
// Preserve trait methods that were previously promoted implicitly.
#deprecated
#doc(hidden)
pub extend ChangeTarget with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend CommitRef with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend FileDiffMode with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend RepositoryRef with Eq::{not_equal, equal}

///|
#deprecated
#doc(hidden)
pub extend Revision with Eq::{not_equal, equal}
